version: "{build}"

environment:
  matrix:
    # node.js
    - nodejs_version: "5.0"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off
